#!/bin/bash

############################################
#               dotfiles                   #
#   git@github.com:altoduo/dotfiles.git    #
#             Setup Script                 #
############################################

git submodule sync
git submodule update --init --recursive
git submodule foreach git pull origin master

if [ "$DOTFILES_PATH" != "" ]; then
  exit
fi

DOTDIR="dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Using $($DOTDIR) as the location for altoduo's dotfiles"

if [ -f ~/.bashrc ]
  then
    echo "export DOTFILES_PATH=$($DOTDIR)" >> ~/.bashrc
    echo "source \$DOTFILES_PATH/bash/.bashrc" >> ~/.bashrc
elif [ ! -f ~/.bashrc ]
  then
    echo "export DOTFILES_PATH=$($DOTDIR)" > ~/.bashrc
    echo "source \$DOTFILES_PATH/bash/.bashrc" >> ~/.bashrc
    #echo "souce \$DOTFILES_PATH/scripts/spotify/spotibash" >> ~/.bashrc
fi

if [ -f ~/.bash_profile ]
  then
    echo "source \$DOTFILES_PATH/bash/.bash_profile" >> ~/.bash_profile
elif [ ! -f ~/.bash_profile ]
  then
    echo "source \$DOTFILES_PATH/bash/.bash_profile" > ~/.bash_profile
fi

if [ -f ~/.vimrc ]
  then
    echo "source \$DOTFILES_PATH/vim/.vimrc" >> ~/.vimrc
elif [ ! -f ~/.vimrc ]
  then
    echo "source \$DOTFILES_PATH/vim/.vimrc" > ~/.vimrc
fi

if [ -d ~/.vim ]
  then
    echo "A ~/.vim folder already exists - please manually fix this."
elif [ ! -d ~/.vim ]
  then
    ln -s $($DOTDIR)/vim/.vim ~/.vim
fi

if [ -f ~/.gvimrc ]
  then
    echo "source \$DOTFILES_PATH/vim/.gvimrc" >> ~/.gvimrc
elif [ ! -f ~/.gvimrc ]
  then
    echo "source \$DOTFILES_PATH/vim/.gvimrc" > ~/.gvimrc
fi

if [ -f ~/.gitconfig ]
  then
    echo "[include]" >> ~/.gitconfig
    echo "  path = $($DOTDIR)/git/.gitconfig" >> ~/.gitconfig
elif [ ! -f ~/.gitconfig ]
  then
    echo "[include]" > ~/.gitconfig
    echo "  path = $($DOTDIR)/git/.gitconfig" >> ~/.gitconfig
fi

if [ -f ~/.zshrc ]
  then
    echo "export DOTFILES_PATH=$($DOTDIR)" >> ~/.zshrc
    echo "source \$DOTFILES_PATH/zsh/.zshrc" >> ~/.zshrc
elif [ ! -f ~/.zshrc ]
  then
    echo "export DOTFILES_PATH=$($DOTDIR)" > ~/.zshrc
    echo "source \$DOTFILES_PATH/zsh/.zshrc" > ~/.zshrc
fi

if [ -f ~/.tmux.conf ]
  then
    echo "source \$DOTFILES_PATH/tmux/.tmux.conf" >> ~/.tmux.conf
elif [ ! -f ~/.tmux.conf ]
  then
    echo "source \$DOTFILES_PATH/tmux/.tmux.conf" > ~/.tmux.conf
fi
