#!/bin/bash

echo -n "Ping: "

while [ true ]; do
    # find the current ping time
    PING_TIME=$(ping -c 1 8.8.8.8 | egrep -o time=[0-9]+\.[0-9]+ | sed s/time=//)

    # color output based on ping time
    PT_INT=$(echo $PING_TIME | sed "s/\.[0-9]*//")
    if [ $((PT_INT)) -lt $((100)) ]; then
        COLOR=${Green}
        CHAR=✓
    elif [ $((PT_INT)) -lt $((250)) ]; then
        COLOR=${Yellow}
        CHAR=!
    else
        COLOR=${Red}
        CHAR=X
    fi

    # output the result
    printf "\r${COLOR}${CHAR}    Ping: ${PING_TIME} ms ${Black}"

    # ping once a second
    sleep 1

done
